### ISSUE TITLE
When defaultOpen=true, and you click a Link to. Then the page loads, the Menu animates from collapse and opens

### ISSUE THREAD

**Issue by mapavia** [azouaoui-med/react-pro-sidebar#37]
I have a SubMenu that I want to be always open (defaultOpen=true). When I click to one of my MenuItem with a <Link to>, and when I am redirected to the link, the SubMenu animates from closed then opens. Is there a way to permanently keep a SubMenu open without animation.

**Comment by mladimatija** [comment]
react-pro-sidebar uses `react-slidedown` for transitions. As far as I know there's no way to disable animations via props but you can use CSS to disable them with something like

```css
.pro-sidebar .pro-menu .pro-menu-item.pro-sub-menu .pro-inner-list-item {
  transition-property: none !important;
}
```

Note that CSS selector could and should be optimized, I just took the one already implemented in `_menu.scss`.
