### ISSUE TITLE
Color on Active Menu

### ISSUE THREAD

**Issue by SouengKimmeng** [azouaoui-med/react-pro-sidebar#49]
Hello everyone does any body know how to change color to active when we click on each menu. Thanks in advance

**Comment by parnasmi** [comment]
there is active prop in MenuItem component. Besides, you also can dynamically pass appropriate class via className and style it as you want. I did not try. But it must work. I just going to use the package.

**Comment by ayush-lal** [comment]
@parnasmi are you able to give an example on how the prop active can be used with multiple links?

**Comment by buskerone** [comment]
Same issue here. `active` prop not working as expected.

**Comment by sunmoon-idegu** [comment]
Hello,

I here have a solution below:

1. Add the following to your css file

```css
/* This is for menu item */
.pro-menu-item a.active {
  color: var(--main-blue);  /* put any color you want */
  font-weight: 500;
}

/* This is for submenu item */
.nav-member .react-slidedown .pro-menu-item a.active {
  color: #003642;  /* put any color you want */
  font-weight: 500;
}
```

2. In the file including the prosidebar component, add the following code

```js
const [preActivePage, setPreActivePage] = useState(null) ;
const [activePage, setActivePage] = useState(null) ;

function handleActive(event) {
  event.target.classList.toggle("active") ;
  setActivePage(event.target) ;
  if (preActivePage) preActivePage.classList.remove("active") ;
  setPreActivePage(event.target) ;
}
```

3. Add onClick function to every Link component
```js
<Link to="/" onClick={handleActive}>
```
