### ISSUE TITLE
Sub menu Item Icon doesn't work

### ISSUE THREAD

**Issue by Misbah-Mushtaq** [azouaoui-med/react-pro-sidebar#5]
@azouaoui-med  Icon for submenu items not working
I want to achieve this
![image](https://user-images.githubusercontent.com/57727236/84475466-0ebc6e00-aca6-11ea-9a07-e1d429be1484.png)

**Comment by lgk-bsw** [comment]
The icons are only hidden with CSS:
```css
.pro-sidebar .pro-menu .pro-menu-item.pro-sub-menu .pro-inner-list-item .pro-inner-item > .pro-icon-wrapper {
    display: none;
}
```
That's defined in: https://github.com/azouaoui-med/react-pro-sidebar/blob/master/src/scss/partials/_menu.scss#L166

You could overwrite this with a new CSS rule like this:
```css
.pro-sidebar .pro-menu .pro-menu-item.pro-sub-menu .pro-inner-list-item .pro-inner-item > .pro-icon-wrapper {
    display: inline-block !important;
}
```
